parameters:
  twitch.client.id: '%env(TWITCH_API_CLIENT_ID)%'
  twitch.client.secret: '%env(TWITCH_API_CLIENT_SECRET)%'
  twitch.broadcaster_id: '%env(TWITCH_BROADCASTER_ID)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      string $twitchClientId: '%twitch.client.id%'
      string $twitchClientSecret: '%twitch.client.secret%'
      string $twitchBroadcasterId: '%twitch.broadcaster_id%'

  _instanceof:
    TBoileau\TwitchApi\Api\Endpoint\AbstractOperations:
      tags: ['twitch.api.operations']
    App\ChatBot\CommandHandlerInterface:
      tags: ['twitch.chat_bot.command_handler']

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  TBoileau\TwitchApi\:
    resource: "../vendor/tboileau/twitch-api/src/"
    exclude:
      - "../vendor/tboileau/twitch-api/src/Message"
      - "../vendor/tboileau/twitch-api/src/Test"

  TBoileau\TwitchApi\Command\InstallTwitchCliCommand:
    arguments:
      $twitchCliDir: '%kernel.project_dir%/var/twitch-cli'

  TBoileau\TwitchApi\Command\ServeTwitchMockServerCommand:
    arguments:
      $twitchCliPath: '%kernel.project_dir%/var/twitch-cli/twitch'
      $twitchMockServerPort: '%env(TWITCH_MOCK_SERVER_PORT)%'

  TBoileau\TwitchApi\Api\TwitchApiInterface:
    class: TBoileau\TwitchApi\Api\TwitchApi
    arguments:
      -  !tagged_iterator {tag: twitch.api.operations, default_index_method: getName}

  TBoileau\TwitchApi\HttpClient:
    factory: ['App\Twitch\HttpClientFactory', 'create']
    arguments:
      $baseUri: '%env(TWITCH_API_BASE_URI)%'
      $clientId: '%env(TWITCH_API_CLIENT_ID)%'

  App\Twitch\OAuth\TwitchAuthenticator:
    arguments:
      $operations: !tagged_iterator twitch.api.operations

  App\Command\TwitchChatBotCommand:
    arguments:
      $commandHandlers: !tagged_iterator twitch.chat_bot.command_handler

  GhostZero\Tmi\Client:
    factory: ['App\Tmi\ClientFactory', 'create']
