parameters:
  twitch.client.id: '%env(TWITCH_CLIENT_ID)%'
  twitch.client.secret: '%env(TWITCH_CLIENT_SECRET)%'
  twitch.broadcaster_id: '%env(TWITCH_BROADCASTER_ID)%'
  social_networks.youtube: '@@toham'
  social_networks.twitter: '@@toham_tech'
  social_networks.github: '@@TBoileau'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      string $twitchClientId: '%twitch.client.id%'
      string $twitchClientSecret: '%twitch.client.secret%'
      string $twitchBroadcasterId: '%twitch.broadcaster_id%'

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
